name: deploy
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Krok 1 - Uses the major version of a release
        # Odniesienie się do głównego wydania aplikacji
        uses: actions/checkout@v2
      - name: Krok 2 - Setup .NET Core SDK
        # Pobranie .NET Core SDK
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: 6.0.x
      - name: Krok 3 - Restore dependencies
        # Pobranie paczek Nuget
        run: dotnet restore
      - name: Krok 4 - Build
        # Zbudowanie aplikacji z projektu
        run: dotnet build --no-restore
      - name: Publish
        # Publikacja: 
        # ./...  - określenie ścieżki projektu, który chcemy opublikować
        # -o ...  - określenie ścieżki, do której paczka zostanie wrzucona 
        run: dotnet publish ./RestaurantAPI/RestaurantAPI.csproj -c Release -o ${{ env.DOTNET_ROOT }}/api
  
  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    steps:

